In [1]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors
import scipy as sp
import scipy.stats
import pandas as pd
import numpy as np
from tqdm import tqdm
import itertools
import re
res_digit = r'[0-9]'

# fourier transform
from scipy.fft import fft, ifft

from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.manifold import TSNE



In [2]:
# This is a hack to make the library in the parent folder available for imoprts
# A better solution is by np8 here:
# https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder
import sys
import os
import inspect

thisdir = sys.path[0]
print(f"thisdir = {thisdir}")
parentdir = os.path.dirname(thisdir)
#print(f"parentdir = {parentdir}")
if not parentdir in sys.path:
    print("Adding parent directory to python path")
    sys.path.insert(1, parentdir)
else:
    print("Skipping adding parent direct to path (there already)")

print(f"sys.path =\n{sys.path}")



thisdir = /home/luke/git/external/predicament/notebooks
Adding parent directory to python path
sys.path =
['/home/luke/git/external/predicament/notebooks', '/home/luke/git/external/predicament', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/luke/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages']


In [3]:
## ensure relative path to data directory is sound
# for the notebook we need to modify the BASE_DATA_FOLDER
import os 
os.environ['PREDICAMENT_DATA_DIR'] =  '../data'

from predicament.utils.config import FEATURED_BASE_PATH

In [4]:
from predicament.utils.file_utils import load_dataframe_and_config

from predicament.evaluation.balancing import get_group_label_counts
from predicament.evaluation.balancing import balance_data
from predicament.evaluation.grouping import get_group_assignments
from predicament.evaluation.staging import get_design_matrix
from predicament.evaluation.results import output_model_best_from_results
from predicament.evaluation.results import save_results_df_to_file


## Load features

Before running this, you will need to generate featured data. See README file for details. For the variable `subdir` below replace this with the subdirectory name of the featured data.

In [5]:
subdir = '20231206193533'
featured_data_dir = os.path.join(FEATURED_BASE_PATH,subdir)

featured_df, featured_config = load_dataframe_and_config(
    featured_data_dir, 'featured.csv')
n_channels = int(featured_config['LOAD']['n_channels'])
channels = json.loads(featured_config['LOAD']['channels'].replace("'",'"'))
participant_list = json.loads(featured_config['LOAD']['participant_list'].replace("'",'"'))
Fs = int(featured_config['LOAD']['sample_rate'])
window_size = int(featured_config['LOAD']['window_size'])
time = window_size/Fs
print(f"Fs: {Fs}, n_samples = {window_size}, time: {time}s, n_channels: {n_channels}")


Fs: 64, n_samples = 256, time: 4.0s, n_channels: 7


In [6]:
featured_df.columns

Index(['participant', 'condition', 'start time', 'Mean0', 'Mean1', 'Mean2',
       'Mean3', 'Mean4', 'Mean5', 'Mean6',
       ...
       'FreqKurtosis4', 'FreqKurtosis5', 'FreqKurtosis6',
       'LempelZivEntropy[b=1][0]', 'LempelZivEntropy[b=1][1]',
       'LempelZivEntropy[b=1][2]', 'LempelZivEntropy[b=1][3]',
       'LempelZivEntropy[b=1][4]', 'LempelZivEntropy[b=1][5]',
       'LempelZivEntropy[b=1][6]'],
      dtype='object', length=157)

In [7]:
# balance featured data
subject_condition_counts = get_group_label_counts(featured_df, 'participant', 'condition')
print(f"before balancing: subject_condition_counts = {subject_condition_counts}")
featured_df = balance_data(featured_df, group_col='participant', label_col='condition')
subject_condition_counts = get_group_label_counts(featured_df, 'participant', 'condition')

print(f"after balancing: subject_condition_counts = {subject_condition_counts}")

before balancing: subject_condition_counts = [[ 833.  473.  473.  473.  473.]
 [ 833.  113.  353.  473.  353.]
 [ 833.  233.  473.  473.  473.]
 [ 833.  593.  353.  233.  473.]
 [   0.  113.    0. 1073.  353.]
 [ 853.  433.    0.  517.  373.]
 [ 833.  593.  473.  353.   89.]
 [ 833.  593.    0.  353.  353.]
 [ 823.  333.    0.  565.  357.]
 [ 953.  473.  353.  473.  353.]
 [ 713.  593.  473.  353.  473.]]
after balancing: subject_condition_counts = [[296. 312. 473. 272. 287.]
 [296. 113. 353. 272. 287.]
 [296. 233. 473. 272. 287.]
 [296. 312. 353. 233. 287.]
 [  0. 113.   0. 272. 287.]
 [296. 312.   0. 272. 287.]
 [296. 312. 473. 272.  89.]
 [296. 312.   0. 272. 287.]
 [296. 312.   0. 272. 287.]
 [296. 312. 353. 272. 287.]
 [296. 312. 473. 272. 287.]]


## Prepare Parameter Search Experiment

In [8]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV 
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import GroupKFold
from skopt import BayesSearchCV
# parameter ranges are specified by one of below
from skopt.space import Real, Categorical, Integer


In [9]:
# model name
name = 'RandomForest'

# extract input data
feature_types, feature_names, designmtx = get_design_matrix(featured_df)
# extract labels
condition_data = featured_df['condition'].values.astype(int)

# prepare Hold one group out cross validation
held_out = 'participant'
held_out, groups, group_assignments = get_group_assignments(featured_df)
n_groups = len(groups)
# cross validation splits    
group_kfold = GroupKFold(n_splits=n_groups)

# choose which search to perform
# search_type = 'random_search'
search_type = 'bayesian_optimization'
# number of iterations for your search
n_iter = 50

feature_type_pairs = [('participant', 'participant'), ('condition', 'condition'), ('start time', 'start'), ('Mean0', 'Mean'), ('Mean1', 'Mean'), ('Mean2', 'Mean'), ('Mean3', 'Mean'), ('Mean4', 'Mean'), ('Mean5', 'Mean'), ('Mean6', 'Mean'), ('SD0', 'SD'), ('SD1', 'SD'), ('SD2', 'SD'), ('SD3', 'SD'), ('SD4', 'SD'), ('SD5', 'SD'), ('SD6', 'SD'), ('MAD0', 'MAD'), ('MAD1', 'MAD'), ('MAD2', 'MAD'), ('MAD3', 'MAD'), ('MAD4', 'MAD'), ('MAD5', 'MAD'), ('MAD6', 'MAD'), ('Max0', 'Max'), ('Max1', 'Max'), ('Max2', 'Max'), ('Max3', 'Max'), ('Max4', 'Max'), ('Max5', 'Max'), ('Max6', 'Max'), ('Min0', 'Min'), ('Min1', 'Min'), ('Min2', 'Min'), ('Min3', 'Min'), ('Min4', 'Min'), ('Min5', 'Min'), ('Min6', 'Min'), ('Energy0', 'Energy'), ('Energy1', 'Energy'), ('Energy2', 'Energy'), ('Energy3', 'Energy'), ('Energy4', 'Energy'), ('Energy5', 'Energy'), ('Energy6', 'Energy'), ('IQR0', 'IQR'), ('IQR1', 'IQR'), ('IQR2', 'IQR'), ('IQR3', 'IQR'), ('IQR4', 'IQR'), ('IQR5', 'IQR'), ('IQR6', 'IQR'), ('Correlation0', '

## Random Search

If `search_type == 'random_search'`, we use a random grid to search for best hyperparameters


In [11]:
if search_type == 'random_search':
    # Number of trees in random forest
    n_estimators = [int(x) for x in np.linspace(start = 10, stop = 200, num = 10)]
    # Number of features to consider at every split
    max_features = ['auto', 'sqrt']
    # Maximum number of levels in tree
    max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
    max_depth.append(None)
    # Minimum number of samples required to split a node
    min_samples_split = [2, 5, 10]
    # Minimum number of samples required at each leaf node
    min_samples_leaf = [1, 2, 4]
    # Method of selecting samples for training each tree
    bootstrap = [True, False] 
    # Create the random grid
    random_grid = {
        'n_estimators': n_estimators,
        'max_features': max_features,
        'max_depth': max_depth,
        'min_samples_split': min_samples_split,
        'min_samples_leaf': min_samples_leaf,
        'bootstrap': bootstrap}

    # First create the base model to tune
    estimator = RandomForestClassifier()
    # Random search of parameters, using 3 fold cross validation, 
    # search across 100 different combinations, and use all available cores
    param_search = RandomizedSearchCV(
        estimator = estimator,
        param_distributions = random_grid,
        n_iter = n_iter,
        cv=group_kfold,
        verbose=2,
        random_state=42,
        n_jobs = -1)

    # Fit the random search model
    _ = param_search.fit(X=designmtx, y=condition_data, groups=group_assignments)


## Bayesian Optimisation

If `search_type == 'bayesian_optimization'`, we use a Bayesian Optimisation search for best hyperparameters. Should be quicker and more effective than random search

In [13]:
# Bayesian optimisation

if search_type == 'bayesian_optimization':

    # this is just a naive initial guess at what will work
    # note that the log-uniform prior helps to focus on 
    # smaller values
    search_spaces = dict(
        # Number of trees in random forest
        n_estimators = Integer(10,2000, prior='log-uniform'),
        # Number of features to consider at every split
        max_features = Categorical(['auto', 'sqrt']),
        # Maximum number of levels in tree
        max_depth = Integer(1, 200,  prior='log-uniform'),
        # Minimum number of samples required at each leaf node
        min_samples_leaf = Real(1e-4, 1e-2, prior='log-uniform'),
        # Method of selecting samples for training each tree
        bootstrap = Categorical([True, False])
    )

    estimator = RandomForestClassifier()
    # log-uniform: understand as search over p = exp(x) by varying x
    param_search = BayesSearchCV(
        estimator, search_spaces,
        cv=group_kfold, verbose=2, random_state=42, n_iter=n_iter,
        n_jobs = -1)

    # executes bayesian optimization
    _ = param_search.fit(X=designmtx, y=condition_data, groups=group_assignments)


Fitting 11 folds for each of 1 candidates, totalling 11 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  11 out of  11 | elapsed:  4.2min finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 11 folds for each of 1 candidates, totalling 11 fits


[Parallel(n_jobs=-1)]: Done  11 out of  11 | elapsed:  5.7min finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 11 folds for each of 1 candidates, totalling 11 fits


[Parallel(n_jobs=-1)]: Done  11 out of  11 | elapsed:   19.9s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 11 folds for each of 1 candidates, totalling 11 fits


[Parallel(n_jobs=-1)]: Done  11 out of  11 | elapsed:   18.4s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 11 folds for each of 1 candidates, totalling 11 fits


[Parallel(n_jobs=-1)]: Done  11 out of  11 | elapsed:  7.6min finished


## Saving and outputing results

In [14]:
result_df = pd.DataFrame(param_search.cv_results_)
result_df.insert(0, 'model', str(estimator))
result_df.insert(1, 'held out', held_out)
result_df.insert(2, 'feature set', str(feature_types))
display(result_df)
save_results_df_to_file(result_df, f'{search_type}_{name}')

model     held out  \
0  RandomForestClassifier()  participant   
1  RandomForestClassifier()  participant   
2  RandomForestClassifier()  participant   
3  RandomForestClassifier()  participant   
4  RandomForestClassifier()  participant   

                                         feature set  mean_fit_time  \
0  {'Energy', 'LempelZivEntropy', 'MAD', 'IQR', '...      80.860373   
1  {'Energy', 'LempelZivEntropy', 'MAD', 'IQR', '...     112.571651   
2  {'Energy', 'LempelZivEntropy', 'MAD', 'IQR', '...       6.493225   
3  {'Energy', 'LempelZivEntropy', 'MAD', 'IQR', '...       5.968149   
4  {'Energy', 'LempelZivEntropy', 'MAD', 'IQR', '...     151.915508   

   std_fit_time  mean_score_time  std_score_time param_bootstrap  \
0      5.315280         0.087075        0.018155           False   
1      6.588301         0.226844        0.057989            True   
2      0.515957         0.008298        0.002013           False   
3      0.394589         0.032742        0.008793            True   
4      7.300137         0.292973        0.068554            True   

  param_max_depth param_max_features  ... split4_test_score split5_test_score  \
0              47               sqrt  ...          0.255908          0.368932   
1             108               auto  ...          0.256583          0.386269   
2             130               auto  ...          0.167454          0.325243   
3               2               sqrt  ...          0.256583          0.378641   
4              10               sqrt  ...          0.251857          0.384189   

  split6_test_score  split7_test_score  split8_test_score  split9_test_score  \
0          0.289932           0.271637           0.335047           0.000000   
1          0.211961           0.276778           0.371894           0.000000   
2          0.143830           0.282776           0.373608           0.003428   
3          0.090083           0.248500           0.245930           0.000000   
4          0.242998           0.275064           0.305056           0.000000   

   split10_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.037202         0.250137        0.156475                1  
1            0.069940         0.241407        0.156945                2  
2            0.101190         0.226939        0.155173                4  
3            0.000000         0.219426        0.144537                5  
4            0.141369         0.237144        0.132369                3  

[5 rows x 27 columns]

saving to ../data/results/bayesian_optimization_RandomForest_2023-12-28T19:06:57.csv


In [16]:
_ = output_model_best_from_results(result_df)

RandomForestClassifier(): max_test_score= 0.2501365821568324, max_std_test_score= 0.15647530693538286
best params: OrderedDict([('bootstrap', False), ('max_depth', 47), ('max_features', 'sqrt'), ('min_samples_leaf', 0.0004281531928076346), ('n_estimators', 348)])

