In [1]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors
import scipy as sp
import scipy.stats
import pandas as pd
import numpy as np
from tqdm import tqdm
import itertools
import re
res_digit = r'[0-9]'

# fourier transform
from scipy.fft import fft, ifft

from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.manifold import TSNE



In [2]:
# This is a hack to make the library in the parent folder available for imoprts
# A better solution is by np8 here:
# https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder
import sys
import os
import inspect

thisdir = sys.path[0]
print(f"thisdir = {thisdir}")
parentdir = os.path.dirname(thisdir)
#print(f"parentdir = {parentdir}")
if not parentdir in sys.path:
    print("Adding parent directory to python path")
    sys.path.insert(1, parentdir)
else:
    print("Skipping adding parent direct to path (there already)")

print(f"sys.path =\n{sys.path}")



thisdir = /home/luke/git/external/predicament/notebooks
Adding parent directory to python path
sys.path =
['/home/luke/git/external/predicament/notebooks', '/home/luke/git/external/predicament', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/luke/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages']


In [3]:
## ensure relative path to data directory is sound
# for the notebook we need to modify the BASE_DATA_FOLDER
import os 
os.environ['PREDICAMENT_DATA_DIR'] =  '../data'

from predicament.utils.config import DREEM_EEG_CHANNELS

In [4]:
from predicament.data.timeseries import create_participant_data_edf_only
from predicament.data.windowed import window_all_participants_data
from predicament.data.windowed import merge_condition_data
from predicament.data.partitioning import between_subject_cv_partition

from predicament.data.features import MAXIMAL_FEATURE_GROUP
from predicament.data.features import STATS_FEATURE_GROUP
from predicament.data.features import INFO_FEATURE_GROUP
from predicament.data.features import FREQ_FEATURE_GROUP
from predicament.data.features import convert_timeseries_to_features
from prepare_evaluation_data import load_dataframe_and_config

from predicament.evaluation.balancing import get_group_label_counts
from predicament.evaluation.balancing import balance_data
# from predicament.data.datasets import propose_balanced_subject_condition_counts
# from predicament.data.datasets import subsample_proposed_subject_condition_counts
# from predicament.data.datasets import get_subject_condition_counts

from predicament.evaluation.results import output_model_best_from_results
from predicament.evaluation.results import save_results_df_to_file


## Load features


In [5]:
featured_df, featured_config = load_dataframe_and_config(
    '../data/featured/20231129210920/', 'featured.csv')
n_channels = int(featured_config['LOAD']['n_channels'])
channels = json.loads(featured_config['LOAD']['channels'].replace("'",'"'))
participant_list = json.loads(featured_config['LOAD']['participant_list'].replace("'",'"'))
Fs = int(featured_config['LOAD']['sample_rate'])
window_size = int(featured_config['LOAD']['window_size'])
time = window_size/Fs
print(f"Fs: {Fs}, n_samples = {window_size}, time: {time}s, n_channels: {n_channels}")


Fs: 250, n_samples = 1024, time: 4.096s, n_channels: 5


In [6]:
featured_df.columns

Index(['part_ID', 'condition', 'start time', 'Mean0', 'Mean1', 'Mean2',
       'Mean3', 'Mean4', 'SD0', 'SD1', 'SD2', 'SD3', 'SD4', 'MAD0', 'MAD1',
       'MAD2', 'MAD3', 'MAD4', 'Max0', 'Max1', 'Max2', 'Max3', 'Max4', 'Min0',
       'Min1', 'Min2', 'Min3', 'Min4', 'Energy0', 'Energy1', 'Energy2',
       'Energy3', 'Energy4', 'IQR0', 'IQR1', 'IQR2', 'IQR3', 'IQR4',
       'Correlation0', 'Correlation1', 'Correlation2', 'Correlation3',
       'Correlation4', 'Correlation5', 'Correlation6', 'Correlation7',
       'Correlation8', 'Correlation9', 'arCoeff0', 'arCoeff1', 'arCoeff2',
       'arCoeff3', 'arCoeff4', 'arCoeff5', 'arCoeff6', 'arCoeff7', 'arCoeff8',
       'arCoeff9', 'arCoeff10', 'arCoeff11', 'arCoeff12', 'arCoeff13',
       'arCoeff14', 'arCoeff15', 'arCoeff16', 'arCoeff17', 'arCoeff18',
       'arCoeff19', 'LyapunovExponent0', 'LyapunovExponent1',
       'LyapunovExponent2', 'LyapunovExponent3', 'LyapunovExponent4',
       'MaxFreqInd0', 'MaxFreqInd1', 'MaxFreqInd2', 'MaxFreqI

In [7]:
features_to_use = set(
    ['Mean', 'SD', 'MAD', 'Max', 'Min',# 'SMA',
      'Energy', 'IQR', # 'Entropy',
     'arCoeff', 'Correlation', 'MaxFreqInd', 'MeanFreq', 'FreqSkewness',
    'FreqKurtosis' # , 'EnergyBands'
    ])
columns_to_use = [ col for col in featured_df.columns if re.sub(res_digit, '', col) in features_to_use ]
print(f"columns_to_use = {columns_to_use}")

# designmtx = featured_df[columns_to_use].values 
# condition_data = featured_df['condition'].values.astype(int)
# subject_data_names = featured_df['part_ID']

# design2d = TSNE(n_components=2, init='random', perplexity=3).fit_transform(designmtx)
# print(f"design2d.shape = {design2d.shape}")

columns_to_use = ['Mean0', 'Mean1', 'Mean2', 'Mean3', 'Mean4', 'SD0', 'SD1', 'SD2', 'SD3', 'SD4', 'MAD0', 'MAD1', 'MAD2', 'MAD3', 'MAD4', 'Max0', 'Max1', 'Max2', 'Max3', 'Max4', 'Min0', 'Min1', 'Min2', 'Min3', 'Min4', 'Energy0', 'Energy1', 'Energy2', 'Energy3', 'Energy4', 'IQR0', 'IQR1', 'IQR2', 'IQR3', 'IQR4', 'Correlation0', 'Correlation1', 'Correlation2', 'Correlation3', 'Correlation4', 'Correlation5', 'Correlation6', 'Correlation7', 'Correlation8', 'Correlation9', 'arCoeff0', 'arCoeff1', 'arCoeff2', 'arCoeff3', 'arCoeff4', 'arCoeff5', 'arCoeff6', 'arCoeff7', 'arCoeff8', 'arCoeff9', 'arCoeff10', 'arCoeff11', 'arCoeff12', 'arCoeff13', 'arCoeff14', 'arCoeff15', 'arCoeff16', 'arCoeff17', 'arCoeff18', 'arCoeff19', 'MaxFreqInd0', 'MaxFreqInd1', 'MaxFreqInd2', 'MaxFreqInd3', 'MaxFreqInd4', 'MeanFreq0', 'MeanFreq1', 'MeanFreq2', 'MeanFreq3', 'MeanFreq4', 'FreqSkewness0', 'FreqSkewness1', 'FreqSkewness2', 'FreqSkewness3', 'FreqSkewness4', 'FreqKurtosis0', 'FreqKurtosis1', 'FreqKurtosis2', '

In [8]:
# proposed_subject_condition_counts = propose_balanced_subject_condition_counts(
#     featured_df)
# print(f"proposed_subject_condition_counts = {proposed_subject_condition_counts}")
# proposed_condition_counts = np.sum(proposed_subject_condition_counts, axis=0)
# print(f"proposed_condition_counts = {proposed_condition_counts}")
# proposed_class_balance = proposed_condition_counts/np.sum(proposed_condition_counts)
# print(f"proposed_class_balance = {proposed_class_balance}")

In [9]:
# def subsample_proposed_subject_condition_counts(df, proposed_sc_counts):
#     subjects = np.unique(df['part_ID'])
#     n_subjects = subjects.size
#     conditions = np.unique(df['condition'])
#     n_conditions = conditions.size
#     new_df = pd.DataFrame(columns=df.columns)
#     for s, subject in enumerate(subjects):
#         for c, condition in enumerate(conditions):
#             sc_df = df[(df['part_ID'] == subject) & (df['condition'] == condition)]
#             new_df = pd.concat(
#                 (new_df, sc_df.sample(proposed_sc_counts[s,c], replace=False)))
#     return new_df

In [10]:
# def get_subject_condition_counts(df):
#     subjects = np.unique(df['part_ID'])
#     n_subjects = subjects.size
#     conditions = np.unique(df['condition'])
#     n_conditions = conditions.size
#     subject_condition_counts = np.zeros((subjects.size,conditions.size))

#     for s, part_ID in enumerate(subjects): 
#         subj_df = df[df['part_ID'] == part_ID]
#         for c, cond in enumerate(conditions):
#             count = len(subj_df[subj_df['condition'] == cond])
#     #         print(f"count = {count}")
#     #         print(f"{s}-{c} : {count}/{tot} = {count/tot}")
#             subject_condition_counts[s,c] = count
#     return subject_condition_counts

In [11]:
# featured_df = subsample_proposed_subject_condition_counts(
#     featured_df, proposed_subject_condition_counts)

In [12]:
# balance featured data
subject_condition_counts = get_group_label_counts(featured_df, 'part_ID', 'condition')
print(f"before balancing: subject_condition_counts = {subject_condition_counts}")
featured_df = balance_data(featured_df, group_col='part_ID', label_col='condition')
subject_condition_counts = get_group_label_counts(featured_df, 'part_ID', 'condition')

print(f"after balancing: subject_condition_counts = {subject_condition_counts}")

before balancing: subject_condition_counts = [[ 813.  461.  461.  461.  461.]
 [ 813.  344.  461.  559.  461.]
 [ 813.  110.  344.  461.  344.]
 [ 813.  227.  461.  461.  461.]
 [ 813.  578.  344.  227.  461.]
 [   0.  110.    0. 1047.  344.]
 [ 832.  422.    0.  504.  364.]
 [ 813.  578.  461.  344.   86.]
 [ 813.  578.    0.  344.  344.]
 [ 803.  325.    0.  551.  348.]
 [ 930.  461.  344.  461.  344.]
 [ 696.  578.  461.  344.  461.]]
after balancing: subject_condition_counts = [[304. 322. 461. 283. 296.]
 [304. 322. 461. 283. 296.]
 [304. 110. 344. 283. 296.]
 [304. 227. 461. 283. 296.]
 [304. 322. 344. 227. 296.]
 [  0. 110.   0. 283. 296.]
 [304. 322.   0. 283. 296.]
 [304. 322. 461. 283.  86.]
 [304. 322.   0. 283. 296.]
 [304. 322.   0. 283. 296.]
 [304. 322. 344. 283. 296.]
 [304. 322. 461. 283. 296.]]


## Visualising data

In [ ]:
subjects = np.unique(subject_data_names)
subject_data = np.empty(subject_data_names.shape, dtype=int)
for s, sub in enumerate(subjects):
    subject_data[subject_data_names==sub] = s
print(f"designmtx.shape = {designmtx.shape}")
print(f"condition_data.shape = {condition_data.shape}")
print(f"subject_data.shape = {subject_data.shape}")
    
conditions = np.unique(condition_data)
markers = ['v', '^', '<', '>', 's', '*', '+' , 'x', 'D', '.']
colours = ['b','g','r','y','k']
cmap = plt.cm.rainbow
norm = colors.BoundaryNorm(np.arange(np.min(subject_data)-0.5,np.max(subject_data)+0.5), cmap.N)

plt.scatter(
    design2d[:,0], design2d[:,1], c=subject_data, norm=norm, s=0.5, edgecolor='none')
plt.colorbar(
    ticks=np.arange(subjects.size))


plt.figure()
cmap = plt.cm.rainbow
norm = colors.BoundaryNorm(np.arange(np.min(condition_data)-0.5,np.max(condition_data)+0.5), cmap.N)

plt.scatter(
    design2d[:,0], design2d[:,1], c=condition_data, norm=norm, s=0.5, edgecolor='none')
plt.colorbar(
    ticks=np.arange(conditions.size))
# for s,subject in enumerate(subjects):
#     marker = s
#     for c, condition in enumerate(conditions):
#         _filter = (condition_data==condition) &(subject_data==subject)
#         #print(f"condition = {condition}")
#         #print(f"np.sum(_filter) = {np.sum(_filter)}")
#         plt.plot(design2d[_filter,0], design2d[_filter,1], ls='None', marker=markers[s], color=colours[c], markeredgewidth=0.1)
        

## Classification

In [ ]:
import pandas as pd

from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.model_selection import GroupKFold

models = {
    "Random Forest": RandomForestClassifier(
        min_samples_leaf=5, random_state=0
    ),
    "Gradient Boosting": GradientBoostingClassifier(
        max_leaf_nodes=15, random_state=0
    ),
    "MLP":  MLPClassifier(max_iter=100)
}
param_grids = {
    "Random Forest": {"n_estimators": [10, 20, 50, 100]},
    "Gradient Boosting": {"n_estimators": [10, 20, 50, 100]},
    "MLP": {
        'hidden_layer_sizes': [(10,),(20,),(50,),(100,)],
        'activation': ['relu'],
        'solver': ['sgd', 'adam'],
        'alpha': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05],
        'learning_rate': ['constant','adaptive'],
    }
}

# determine the columns to use
features_to_use = set(
    ['Mean', 'SD', 'MAD', 'Max', 'Min',# 'SMA',
      'Energy', 'IQR', # 'Entropy',
     'arCoeff', 'Correlation', 'MaxFreqInd', 'MeanFreq', 'FreqSkewness',
    'FreqKurtosis' # , 'EnergyBands'
    ])
columns_to_use = [ col for col in featured_df.columns if re.sub(res_digit, '', col) in features_to_use ]
print(f"columns_to_use = {columns_to_use}")

designmtx = featured_df[columns_to_use].to_numpy()

condition_data = featured_df['condition'].values.astype(int)


## Hold one group out

In [ ]:
# standard cross-validation
# Match all digits in the string and replace them with an empty string
# new_string = re.sub(pattern, '', string1)
subjects = np.unique(featured_df['part_ID'])
n_subjects = len(subjects)
groups = np.empty(len(featured_df), dtype=int)
for s, sub in enumerate(subjects):
    groups[featured_df['part_ID']==sub] = s
# cross validation splits    
group_kfold = GroupKFold(n_splits=n_subjects)


In [ ]:
results_df = pd.DataFrame()
results = []
for name, model in models.items():
    grid_search = GridSearchCV(
        estimator=model,
        param_grid=param_grids[name],
        return_train_score=True,
        cv=group_kfold,
    ).fit(X=designmtx, y=condition_data, groups=groups)
    result_df = pd.DataFrame(grid_search.cv_results_)
    #test_df['model'] = result['model']
    result_df.insert(0, 'model', name)
    result_df.insert(1, 'held out', 'subject')
    result_df.insert(2, 'feature set', str(features_to_use))
    display(result_df)
    results_df = pd.concat((results_df, result_df))
    #result = {"model": name, "cv_results": pd.DataFrame(grid_search.cv_results_)}
    #results.append(result)

In [ ]:
from importlib import reload
import predicament.evaluation.results
reload(predicament.evaluation.results)
from predicament.evaluation.results import test
from predicament.evaluation.results import save_results_df_to_file
results_df

In [ ]:
save_results_df_to_file(results_df, 'balanced_eeg')

In [ ]:
output_model_best_from_results(results_df)

In [ ]:
results_df

## Random Search

In [ ]:
from sklearn.model_selection import RandomizedSearchCV 
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]# Create the random grid
random_grid = {
    'n_estimators': n_estimators,
    'max_features': max_features,
    'max_depth': max_depth,
    'min_samples_split': min_samples_split,
    'min_samples_leaf': min_samples_leaf,
    'bootstrap': bootstrap}

In [ ]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(
    estimator = rf,
    param_distributions = random_grid,
    n_iter = 100,
    cv=group_kfold,
    verbose=2,
    random_state=42,
    n_jobs = -1)


# Fit the random search model
rf_random.fit(X=designmtx, y=condition_data, groups=groups)
random_result_df = pd.DataFrame(rf_random.cv_results_)
save_results_df_to_file(random_result_df, 'random_search_random_forest')

In [ ]:
# # focus on MLP model
# name = "MLP"  
# mlp_param_grid = dict(
#     hidden_layer_sizes=[(10*i,) for i in range(1,21)],
# #     activation=['tanh', 'relu'],
# #     solver=['sgd', 'adam'],
#     alpha=np.logspace(-5,-1,13),
# #     learning_rate=['constant','adaptive'],
#     #learning_rate_init=np.logspace(-5,-1,13),
#     max_iter=[50, 100, 150, 200]
#     )

# for param in mlp_param_grid.keys():
#     these_static_params = { k:v for k, v in mlp_best_params.items() if k != param }
#     model = MLPClassifier(**these_static_params)
#     this_param_grid = { k:v for k,v in mlp_param_grid.items() if k == param }
#     grid_search = GridSearchCV(
#         estimator=model,
#         param_grid=this_param_grid,
#         return_train_score=True,
#         cv=group_kfold,
#     ).fit(X=designmtx, y=condition_data, groups=groups)
#     result_df = pd.DataFrame(grid_search.cv_results_)
#     #test_df['model'] = result['model']
#     result_df.insert(0, 'model', name)
#     result_df.insert(1, 'held out', 'subject')
#     result_df.insert(2, 'feature set', str(features_to_use))
#     display(result_df)
#     results_df = pd.concat((results_df, result_df))


In [ ]:
# Bayesian optimisation

from skopt import BayesSearchCV
# parameter ranges are specified by one of below
from skopt.space import Real, Categorical, Integer

# from sklearn.datasets import load_iris
# from sklearn.svm import SVC
# from sklearn.model_selection import train_test_split

# X, y = load_iris(True)
# X_train, X_test, y_train, y_test = train_test_split(X, y,
#      train_size=0.75,
#     random_state=0)

# estimator = SVC()
# search_spaces =      {
#          'C': Real(1e-6, 1e+6, prior='log-uniform'),
#          'gamma': Real(1e-6, 1e+1, prior='log-uniform'),
#          'degree': Integer(1,8),
#          'kernel': Categorical(['linear', 'poly', 'rbf']),
#      }
estimator = MLPClassifier(max_iter=100)
#     "MLP": {
#         'hidden_layer_sizes': [(10,),(20,),(50,),(100,)],
#         'activation': ['relu'],
#         'solver': ['sgd', 'adam'],
#         'alpha': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05],
#         'learning_rate': ['constant','adaptive'],
#     }
search_spaces =      {
        'hidden_layer_sizes': Categorical([ (n,) for n in range(10,200,10)]),
        'activation': Categorical(['tanh', 'relu']),
        'solver': Categorical(['sgd', 'adam']),
        'alpha': Real(1e-6, 1e+1, prior='log-uniform'),
        'learning_rate': Categorical(['constant','adaptive']),
     }

# log-uniform: understand as search over p = exp(x) by varying x
param_search = BayesSearchCV(
    estimator, search_spaces,
    cv=group_kfold, verbose=2, random_state=42, n_iter=50)

# executes bayesian optimization
_ = param_search.fit(X=designmtx, y=condition_data, groups=groups)
result_df = pd.DataFrame(param_search.cv_results_)
result_df.insert(0, 'model', name)
result_df.insert(1, 'held out', 'subject')
result_df.insert(2, 'feature set', str(features_to_use))
display(result_df)
# results_df = pd.concat((results_df, result_df))

save_results_df_to_file(result_df, 'bayes_search')

# # model can be saved, used for predictions or scoring
# print(opt.score(X_test, y_test))

In [ ]:
dict(result_df[result_df['mean_test_score'] == result_df['mean_test_score'].max()].loc[37])

In [ ]:
# # balancing data
# ## first get the proposed new counts of each subject and condition
# def propose_balanced_subject_condition_counts(df):
#     subjects = np.unique(df['part_ID'])
#     n_subjects = subjects.size
#     conditions = np.unique(df['condition'])
#     n_conditions = conditions.size
# #     tot = len(df)
#     subject_condition_counts = np.zeros((subjects.size,conditions.size), dtype=int)

#     for s, part_ID in enumerate(subjects): 
#         subj_df = df[df['part_ID'] == part_ID]
#         for c, cond in enumerate(conditions):
#             count = len(subj_df[subj_df['condition'] == cond])
#     #         print(f"count = {count}")
#     #         print(f"{s}-{c} : {count}/{tot} = {count/tot}")
#             subject_condition_counts[s,c] = count

#     # print(f"subject_condition_counts = {subject_condition_counts}")
#     condition_counts = np.sum(subject_condition_counts, axis=0)
#     # print(f"condition_counts = {condition_counts}")
#     desired_condition_count = np.min(condition_counts)
#     # print(f"desired_condition_count = {desired_condition_count}")
#     proposed_subject_condition_counts = np.ones(subject_condition_counts.shape)*desired_condition_count//len(subjects)
#     proposed_subject_condition_counts = np.minimum(subject_condition_counts, proposed_subject_condition_counts)
#     to_allocate = desired_condition_count - np.sum(proposed_subject_condition_counts, axis=0)
#     while np.any(to_allocate >= n_subjects):
#         proposed_subject_condition_counts += (to_allocate//n_subjects).reshape((1,-1))
#         proposed_subject_condition_counts = np.minimum(subject_condition_counts,proposed_subject_condition_counts)
#         to_allocate = desired_condition_count - np.sum(proposed_subject_condition_counts, axis=0)
#     # print(f"proposed_subject_condition_counts = {proposed_subject_condition_counts}")
#     # print(f"to_allocate = {to_allocate}")
#     proposed_condition_counts = np.sum(proposed_subject_condition_counts, axis=0)
#     # print(f"proposed_condition_counts = {proposed_condition_counts}")
#     proposed_class_balance = proposed_condition_counts/np.sum(proposed_condition_counts)
#     # print(f"proposed_class_balance = {proposed_class_balance}")
#     # print("add one to cells with the capacity...")
#     while np.any(to_allocate > 0):
#         proposed_subject_condition_counts[(subject_condition_counts > proposed_subject_condition_counts) & (to_allocate.reshape((1,-1)) > 0)] += 1
#         #print(f"proposed_subject_condition_counts = {proposed_subject_condition_counts}")
#         to_allocate = desired_condition_count - np.sum(proposed_subject_condition_counts, axis=0)
#         #print(f"to_allocate = {to_allocate}")
#     return proposed_subject_condition_counts.astype(int)
    

# Balanced data 



In [ ]:
subjects = np.unique(balanced_featured_df['part_ID'])
n_subjects = len(subjects)
groups = np.empty(len(balanced_featured_df), dtype=int)
for s, sub in enumerate(subjects):
    groups[balanced_featured_df['part_ID']==sub] = s
    
features_to_use = set(
    ['Mean', 'SD', 'MAD', 'Max', 'Min',# 'SMA',
      'Energy', 'IQR', # 'Entropy',
     'arCoeff', 'Correlation', 'MaxFreqInd', 'MeanFreq', 'FreqSkewness',
    'FreqKurtosis' # , 'EnergyBands'
    ])
columns_to_use = [ col for col in balanced_featured_df.columns if re.sub(res_digit, '', col) in features_to_use ]
print(f"columns_to_use = {columns_to_use}")

In [ ]:
designmtx = balanced_featured_df[columns_to_use].values 
condition_data = balanced_featured_df['condition'].values.astype(int)

balanced_results_df = pd.DataFrame()
group_kfold = GroupKFold(n_splits=n_subjects)
results = []
for name, model in models.items():
    grid_search = GridSearchCV(
        estimator=model,
        param_grid=param_grids[name],
        return_train_score=True,
        cv=group_kfold,
    ).fit(X=designmtx, y=condition_data, groups=groups)
    result_df = pd.DataFrame(grid_search.cv_results_)
    #test_df['model'] = result['model']
    result_df.insert(0, 'model', name)
    result_df.insert(1, 'held out', 'subject')
    result_df.insert(2, 'feature set', str(features_to_use))
    display(result_df)
    balanced_results_df = pd.concat((balanced_results_df, result_df))
    #result = {"model": name, "cv_results": pd.DataFrame(grid_search.cv_results_)}
    #results.append(result)

In [ ]:
# def output_model_best_from_results(results_df):
#     for model in np.unique(results_df['model']):
#         model_max_test_score = results_df[results_df['model'] == model]['mean_test_score'].max()
#         model_max_std_test_score = results_df[(results_df['model'] == model) & (results_df['mean_test_score']==model_max_test_score)]['std_test_score'].to_numpy()[0]
#         print(f"{model}: max_test_score= {model_max_test_score}, max_std_test_score= {model_max_std_test_score}")
#         d = results_df[results_df['mean_test_score'] == model_max_test_score]['params']
#         for k,v in d.items():
#             model_best_params = v
#             print(f"best params: {v}")
#         print()


In [ ]:
# def save_results_df_to_file(df, shortname, timestamp=True):
#     import datetime
#     nowstr = datetime.datetime.now().replace(microsecond=0).isoformat()
#     if timestamp:
#         name = shortname + '_' + nowstr
#     else:
#         name = shortname
#     fpath = f'../data/results/{name}.csv'
#     print(f"saving to {fpath}")
#     results_df.to_csv(fpath)
